version: "3"
services:
  neo4j:
    image: neo4j:4.1.1
    container_name: neo4j
    volumes:
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_data:/data
      - neo4j_log:/var/lib/neo4j/logs
    restart: always
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_dbms_memory_heap_maxSize=4G
      - NEO4J_AUTH=neo4j/123456  #修改默认用户密码
      - NEO4J_dbms_directories_import=/var/lib/neo4j/import
      - NEO4J_dbms_directories_logs=/var/lib/neo4j/logs
      
volumes: 
  neo4j_import:
    name: neo4j_import
  neo4j_data:
    name: neo4j_data
  neo4j_log:
    name: neo4j_log
