version: '3.4'

services:
  mongodb:
    image: mongo:3.6.21
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    environment:
      TZ: Asia/Shanghai
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    volumes:
      - mongo_data:/data/db
      - /etc/localtime:/etc/localtime

volumes:
  mongo_data:
    name: mongo_data
