version: "3.4"
services:
  mysql-legacy:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: csc
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql:rw
      - ./my.cnf:/etc/mysql/conf.d/config-file.cnf

volumes:
  mysql_data:
    name: mysql_data
